name: Build

on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".clang-format"
  pull_request:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".clang-format"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential g++-14 git make pkg-config cmake ninja-build \
            gnome-desktop-testing libasound2-dev libpulse-dev \
            libaudio-dev libfribidi-dev libjack-dev libsndio-dev \
            libx11-dev libxext-dev libxrandr-dev libxcursor-dev \
            libxfixes-dev libxi-dev libxss-dev libxtst-dev \
            libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev \
            libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev \
            libibus-1.0-dev libudev-dev libthai-dev \
            libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev
      - name: Configure CMake
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-14
          else
            cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
          fi
        shell: bash

      - name: Build
        run: cmake --build build --config Release

      - name: Save Linux Artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: chip8-linux
          path: build/chip8-emulator

      - name: Save Windows Artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: chip8-windows
          path: |
            build/Release/chip8-emulator.exe
            build/Release/*.dll
